### ISSUE TITLE
It seems that there is a wrong if statement.

### ISSUE THREAD

**Issue by hktt-git** [shooter64738/grbl-mega#11]
When I executed the following g-code and Y axis changed from negative direction to positive direction, the backlash compensation was ignored. 

```
G00 X10 Y0 Z0
G03 X10 Y0 Z0 I-10 J0 F100
```

As the result of my debug, even though Y axis step_diff (in "backlash.h") was zero, "back_lash_compensation.last_comp_direction" was overwritten by 1. It was caused by the if statement in "planner.c".

[https://github.com/shooter64738/grbl-mega/blob/master/planner.c#L393](https://github.com/shooter64738/grbl-mega/blob/master/planner.c#L393) 

I think "target_steps != 0" is mistake but "delta_mm != 0.0" is correct. When the difference between the current position and the "target" position is zero, 
the program should not overwrite the last direction. So in this if statement "delta_mm" should be referenced.

I'm sorry for my poor English and report.

**Comment by romlel** [comment]
Hi. Seems that we are having a similar problem. I just asked some questions on another issue.

I'm not sure I understood your proposition. Could you please copy/paste a snippet of code that should be ok according to you ? I'll have a look on my side also.

Thanks !

**Comment by hktt-git** [comment]
Thank you for your reply.
I suggest fixing "planner.c:393"

from
```
if (target_steps[idx]!=0)
    back_lash_compensation.last_comp_direction[idx] = 1;
```
to
```
if(delta_mm != 0.0)
    back_lash_compensation.last_comp_direction[idx] = 1;
```

**Comment by romlel** [comment]
Ah, yes :) That what one of the fixes I tried from your first comment, and firsts tests seems good.
I added on my working copy a "debug variable" to count the number of compensations done in each direction over time, and with your fix, they stay "in equilibrium", before, the two counters were drifting more and more apart (so compensations were not symetrical.

i'll take it to the physical CNC tomorrow on a real use case, and keep you - and the main author or course- posted
Thanks !

**Comment by romlel** [comment]
Well, it seems to work well. I have to make more tests but first one was positive
Thanks a lot !

@shooter64738 : Do you think this fix is correct ? If so, could you please integrate it in the main code for everyone to enjoy ? thanks

**Comment by shooter64738** [comment]
Sure guys! I have a few tweaks I need to push up to this repo. I'll get this change added as well and compile a new version. Thanks for the efforts.  Also if you have an stm32h7 board the talos project is a much bigger cnc control. I never could get enough interest in it for anyone to lend a hand, but its a commercial grade cnc control. Spent 6 years on it, and Im just running out of interest in it.

**Comment by shooter64738** [comment]
Code and hex is updated. Erroneous print messages for BLC are gone, and correction to the BLC distance was made. Tested on a mega 2560. I'll close this issue now.

Thanks again!
