### ISSUE TITLE
Is it stable version of grbl mega2560

### ISSUE THREAD

**Issue by arlimbad222** [shooter64738/grbl-mega#7]
Can anyone tell is this GRBL is stable currently I use grbl mega 5x . Now my machine screw has a small amount of backlash and need a backlash comp.

**Comment by shooter64738** [comment]
This version of grbl was forked from the main grbl branch so should be stable. The only modifications I made was to port the BL comp code from my control to this one. It shoukd be as stable as the original version.

**Comment by arlimbad222** [comment]
First thankyou so much for quick response .

This is aman from india and I want to use your code to control my cnc .
Have you taste backlash comp  Completely is this any error or modification
needed . Currently I am using android app as a g-code sender.

And do you have any instructions how to use backlash comp etc....
